// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: raft/raftpb/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command       []byte                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type SnapshotState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term          int32                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotState) Reset() {
	*x = SnapshotState{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotState) ProtoMessage() {}

func (x *SnapshotState) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotState.ProtoReflect.Descriptor instead.
func (*SnapshotState) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotState) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *SnapshotState) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotState) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type RequestVoteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int32                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int32                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArgs) Reset() {
	*x = RequestVoteArgs{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArgs) ProtoMessage() {}

func (x *RequestVoteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArgs.ProtoReflect.Descriptor instead.
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteArgs) GetLastLogIndex() int32 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteArgs) GetLastLogTerm() int32 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  int32                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   int32                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesArgs) Reset() {
	*x = AppendEntriesArgs{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesArgs) ProtoMessage() {}

func (x *AppendEntriesArgs) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesArgs.ProtoReflect.Descriptor instead.
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesArgs) GetPrevLogIndex() int32 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesArgs) GetPrevLogTerm() int32 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesArgs) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesArgs) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Term                 int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ConflictingTerm      int32                  `protobuf:"varint,3,opt,name=conflicting_term,json=conflictingTerm,proto3" json:"conflicting_term,omitempty"`
	ConflictingTermStart int32                  `protobuf:"varint,4,opt,name=conflicting_term_start,json=conflictingTermStart,proto3" json:"conflicting_term_start,omitempty"`
	LogLength            int32                  `protobuf:"varint,5,opt,name=log_length,json=logLength,proto3" json:"log_length,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AppendEntriesReply) Reset() {
	*x = AppendEntriesReply{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReply) ProtoMessage() {}

func (x *AppendEntriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReply.ProtoReflect.Descriptor instead.
func (*AppendEntriesReply) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesReply) GetConflictingTerm() int32 {
	if x != nil {
		return x.ConflictingTerm
	}
	return 0
}

func (x *AppendEntriesReply) GetConflictingTermStart() int32 {
	if x != nil {
		return x.ConflictingTermStart
	}
	return 0
}

func (x *AppendEntriesReply) GetLogLength() int32 {
	if x != nil {
		return x.LogLength
	}
	return 0
}

type InstallSnapshotArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Snapshot      *SnapshotState         `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotArgs) Reset() {
	*x = InstallSnapshotArgs{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotArgs) ProtoMessage() {}

func (x *InstallSnapshotArgs) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotArgs.ProtoReflect.Descriptor instead.
func (*InstallSnapshotArgs) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSnapshotArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotArgs) GetSnapshot() *SnapshotState {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type InstallSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotReply) Reset() {
	*x = InstallSnapshotReply{}
	mi := &file_raft_raftpb_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotReply) ProtoMessage() {}

func (x *InstallSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_raft_raftpb_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotReply.ProtoReflect.Descriptor instead.
func (*InstallSnapshotReply) Descriptor() ([]byte, []int) {
	return file_raft_raftpb_raft_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSnapshotReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_raft_raftpb_raft_proto protoreflect.FileDescriptor

const file_raft_raftpb_raft_proto_rawDesc = "" +
	"\n" +
	"\x16raft/raftpb/raft.proto\x12\x04raft\"8\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\"O\n" +
	"\rSnapshotState\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytes\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x05R\x04term\"\x92\x01\n" +
	"\x0fRequestVoteArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x05R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x05R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x05R\vlastLogTerm\"I\n" +
	"\x10RequestVoteReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xdd\x01\n" +
	"\x11AppendEntriesArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x05R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x05R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x05 \x03(\v2\x0e.raft.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x05R\fleaderCommit\"\xc2\x01\n" +
	"\x12AppendEntriesReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12)\n" +
	"\x10conflicting_term\x18\x03 \x01(\x05R\x0fconflictingTerm\x124\n" +
	"\x16conflicting_term_start\x18\x04 \x01(\x05R\x14conflictingTermStart\x12\x1d\n" +
	"\n" +
	"log_length\x18\x05 \x01(\x05R\tlogLength\"w\n" +
	"\x13InstallSnapshotArgs\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12/\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x13.raft.SnapshotStateR\bsnapshot\"*\n" +
	"\x14InstallSnapshotReply\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term2\xd2\x01\n" +
	"\x04Raft\x12<\n" +
	"\vRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReply\x12B\n" +
	"\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\x12H\n" +
	"\x0fInstallSnapshot\x12\x19.raft.InstallSnapshotArgs\x1a\x1a.raft.InstallSnapshotReplyB)Z'6.5840-final-project/raft/raftpb;raftpbb\x06proto3"

var (
	file_raft_raftpb_raft_proto_rawDescOnce sync.Once
	file_raft_raftpb_raft_proto_rawDescData []byte
)

func file_raft_raftpb_raft_proto_rawDescGZIP() []byte {
	file_raft_raftpb_raft_proto_rawDescOnce.Do(func() {
		file_raft_raftpb_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_raftpb_raft_proto_rawDesc), len(file_raft_raftpb_raft_proto_rawDesc)))
	})
	return file_raft_raftpb_raft_proto_rawDescData
}

var file_raft_raftpb_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raft_raftpb_raft_proto_goTypes = []any{
	(*LogEntry)(nil),             // 0: raft.LogEntry
	(*SnapshotState)(nil),        // 1: raft.SnapshotState
	(*RequestVoteArgs)(nil),      // 2: raft.RequestVoteArgs
	(*RequestVoteReply)(nil),     // 3: raft.RequestVoteReply
	(*AppendEntriesArgs)(nil),    // 4: raft.AppendEntriesArgs
	(*AppendEntriesReply)(nil),   // 5: raft.AppendEntriesReply
	(*InstallSnapshotArgs)(nil),  // 6: raft.InstallSnapshotArgs
	(*InstallSnapshotReply)(nil), // 7: raft.InstallSnapshotReply
}
var file_raft_raftpb_raft_proto_depIdxs = []int32{
	0, // 0: raft.AppendEntriesArgs.entries:type_name -> raft.LogEntry
	1, // 1: raft.InstallSnapshotArgs.snapshot:type_name -> raft.SnapshotState
	2, // 2: raft.Raft.RequestVote:input_type -> raft.RequestVoteArgs
	4, // 3: raft.Raft.AppendEntries:input_type -> raft.AppendEntriesArgs
	6, // 4: raft.Raft.InstallSnapshot:input_type -> raft.InstallSnapshotArgs
	3, // 5: raft.Raft.RequestVote:output_type -> raft.RequestVoteReply
	5, // 6: raft.Raft.AppendEntries:output_type -> raft.AppendEntriesReply
	7, // 7: raft.Raft.InstallSnapshot:output_type -> raft.InstallSnapshotReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raft_raftpb_raft_proto_init() }
func file_raft_raftpb_raft_proto_init() {
	if File_raft_raftpb_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_raftpb_raft_proto_rawDesc), len(file_raft_raftpb_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_raftpb_raft_proto_goTypes,
		DependencyIndexes: file_raft_raftpb_raft_proto_depIdxs,
		MessageInfos:      file_raft_raftpb_raft_proto_msgTypes,
	}.Build()
	File_raft_raftpb_raft_proto = out.File
	file_raft_raftpb_raft_proto_goTypes = nil
	file_raft_raftpb_raft_proto_depIdxs = nil
}
