// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kv/kvpb/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_kv_kvpb_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kvpb_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_kv_kvpb_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_kv_kvpb_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kvpb_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_kv_kvpb_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PutArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArgs) Reset() {
	*x = PutArgs{}
	mi := &file_kv_kvpb_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArgs) ProtoMessage() {}

func (x *PutArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kvpb_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArgs.ProtoReflect.Descriptor instead.
func (*PutArgs) Descriptor() ([]byte, []int) {
	return file_kv_kvpb_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutArgs) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_kv_kvpb_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_kv_kvpb_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_kv_kvpb_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_kv_kvpb_kv_proto protoreflect.FileDescriptor

const file_kv_kvpb_kv_proto_rawDesc = "" +
	"\n" +
	"\x10kv/kvpb/kv.proto\x12\x02kv\"\x1b\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"K\n" +
	"\aPutArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"\x1c\n" +
	"\bPutReply\x12\x10\n" +
	"\x03err\x18\x01 \x01(\tR\x03err2H\n" +
	"\x02KV\x12 \n" +
	"\x03Get\x12\v.kv.GetArgs\x1a\f.kv.GetReply\x12 \n" +
	"\x03Put\x12\v.kv.PutArgs\x1a\f.kv.PutReplyB#Z!6.5840-final-project/kv/kvpb;kvpbb\x06proto3"

var (
	file_kv_kvpb_kv_proto_rawDescOnce sync.Once
	file_kv_kvpb_kv_proto_rawDescData []byte
)

func file_kv_kvpb_kv_proto_rawDescGZIP() []byte {
	file_kv_kvpb_kv_proto_rawDescOnce.Do(func() {
		file_kv_kvpb_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_kvpb_kv_proto_rawDesc), len(file_kv_kvpb_kv_proto_rawDesc)))
	})
	return file_kv_kvpb_kv_proto_rawDescData
}

var file_kv_kvpb_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kv_kvpb_kv_proto_goTypes = []any{
	(*GetArgs)(nil),  // 0: kv.GetArgs
	(*GetReply)(nil), // 1: kv.GetReply
	(*PutArgs)(nil),  // 2: kv.PutArgs
	(*PutReply)(nil), // 3: kv.PutReply
}
var file_kv_kvpb_kv_proto_depIdxs = []int32{
	0, // 0: kv.KV.Get:input_type -> kv.GetArgs
	2, // 1: kv.KV.Put:input_type -> kv.PutArgs
	1, // 2: kv.KV.Get:output_type -> kv.GetReply
	3, // 3: kv.KV.Put:output_type -> kv.PutReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kv_kvpb_kv_proto_init() }
func file_kv_kvpb_kv_proto_init() {
	if File_kv_kvpb_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_kvpb_kv_proto_rawDesc), len(file_kv_kvpb_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_kvpb_kv_proto_goTypes,
		DependencyIndexes: file_kv_kvpb_kv_proto_depIdxs,
		MessageInfos:      file_kv_kvpb_kv_proto_msgTypes,
	}.Build()
	File_kv_kvpb_kv_proto = out.File
	file_kv_kvpb_kv_proto_goTypes = nil
	file_kv_kvpb_kv_proto_depIdxs = nil
}
